url: http://www.tekno.mobi
baseurl: http://www.tekno.mobi/

# Site settings
title: Tekno Mobi
email: info@tekno.mobi
description: "We build Web applications that improve your business and life"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 72bcd4
  secondary: 3a7ebf   
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Laith Yousif
  pic: 1
  position: Founder and Chief Technology Officer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

#- name: Dina Ciarmatori
#  pic: 2
#  position: Chief Marketing Officer
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: linkedin
#      url: #

- name: Ghaith Yousif
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: OC Yousif
  pic: 4
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: twitter
#   url: http://twitter.com/teknomobiOffical
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket 
#    url: http://bitbucket.org/lnyousif
  - title: github
    url: http://github.com/lnyousif

# Postal address (add as many lines as necessary)
address:
  - line: 77 Sands St.
  - line: Brooklyn, NY 11201

# Build settings
markdown: kramdown
permalink: pretty

